services:
  go-backend:
    build: .
    env_file:
      - "./config/config.env"
    volumes:
      - ./config/config.env:/app/config/config.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7777:7777"

  postgres:
    image: postgres:alpine
    env_file:
      - ./config/config.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: